### ISSUE TITLE
Duplicate values

### ISSUE THREAD

**Issue by AIstats3** [sealneaward/nba-movement-data#2]
There are duplicate values in shot_fixed.csv files, specifically an issue in SHOT_TIME and location columns. Not sure if the issue extends to unfixed data as well.
For ex:
<img width="2325" alt="image" src="https://github.com/sealneaward/nba-movement-data/assets/145382511/147497d0-040a-4cba-96d1-d0da188eda21">
PS: (If image does not attach lmk, am new to Git)
PPS: (game id 21500476, event ids 313 and 315, player id 1626204: SHOT_TIME=429.44 and (LOC_X,LOC_Y)=(-144.217,106.6109) for both)

**Comment by sealneaward** [comment]
There are probably duplicate values in the `shot_fixed.csv` file because the logic for determining the correct time (and a result, location) can always be flawed for shots that are really close to each other. 

For centers and power forwards that are getting their own offensive rebounds to their own shots, this can definitely be the case where the highest point of acceleration was for their original shot, but the second shot they took after their rebound was within the window of the first shot. As a result, the acceleration logic of the two shots points to the highest point of acceleration, resulting in two shots being recorded at the same time. 

If this is a problem, I would suggest using the non-fixed shot data and not using the fixed shot data. I am always open to PRs that change the data and the logic, but I do not have the time, nor the appetite to fix these repositories anymore. I'm in a completely different field now than sports analytics and I don't really do a lot of work in Python anymore unless it is related to DevOps.
